### ISSUE TITLE
cducrest-brainbot - Incorrect calcuation of getTknOhmPrice

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-olympus-judging#47]
cducrest-brainbot

high

# Incorrect calcuation of getTknOhmPrice

## Summary

The calculation for `getTknOhmPrice` does not use the correct values.

## Vulnerability Detail

We want to output a value that when multiplied by an OHM amount yields wstETH amount. I.e. we want `wstEthPerOhm`. 
Not taking decimals into account, we can calculate it as `wstEthPerOhm = wstEthPerEth * ethPerOhm = wstethPerSteth * stethPerEth * ethPerOhm = stethPerEth * ethPerOhm / stethPerWsteth`

The logic is `APerB = APerC * CPerB` and `APerB = 1 / BPerA`

The calculation uses `stethPerEth` in denominator instead of numerator. 

## Impact

Incorrect value of `getTknOhmPrice()` used to calculate the expected amount of wstEth out during a withdraw, the value of `stethPerEth` is currently `0.9977325266` so the difference is not that big. Too much wstEth will be returned to the user resulting in a financial loss for the protocol.

## Code Snippet

```solidity
    function getTknOhmPrice() public view override returns (uint256) {
        // Get stETH per wstETH (18 Decimals)
        uint256 stethPerWsteth = IWsteth(pairToken).stEthPerToken();

        // Get ETH per OHM (18 Decimals)
        uint256 ethPerOhm = _validatePrice(ohmEthPriceFeed.feed, ohmEthPriceFeed.updateThreshold);

        // Get stETH per ETH (18 Decimals)
        uint256 stethPerEth = _validatePrice(
            stethEthPriceFeed.feed,
            stethEthPriceFeed.updateThreshold
        );

        // Calculate wstETH per OHM (18 decimals)
        return (ethPerOhm * 1e36) / (stethPerWsteth * stethPerEth);
    }
```

https://github.com/sherlock-audit/2023-03-olympus/blob/main/sherlock-olympus/src/policies/BoostedLiquidity/BLVaultManagerLido.sol#L458

## Tool used

Manual Review

## Recommendation

Use `stethPerEth * ethPerOhm / stethPerWsteth` calculation

**Comment by cducrest** [comment]
Escalate for 10 USDC

Comment from protocol https://github.com/sherlock-audit/2023-03-olympus-judging/issues/42#issuecomment-1492267023 states `1 wstETH = 1.1 stETH, 1 stETH = 0.9 ETH, and 1 OHM = 0.01 ETH`

This gives:
- stethPerWsteth = `1.1 / 1 = 1`
- ethPerOhm = `0.01 / 1 = 00.1`
- stethPerEth = `1 / 0.9 = 1.1111...`

Comment also states: `The calculation as it stands now would be 1.1 * 0.9 / 0.01 = 99 OHM which is correct`

The code uses `(stethPerWsteth * stethPerEth) / (ethPerOhm * 1e9) = (1.1 / 0.9) / 0.01 = 122.222` which is incorrect:
https://github.com/sherlock-audit/2023-03-olympus/blob/main/sherlock-olympus/src/policies/BoostedLiquidity/BLVaultManagerLido.sol#L454

The available oracle by chainlink is stETH / ETH and not ETH / stETH: https://data.chain.link/ethereum/mainnet/crypto-eth/steth-eth.

If the protocol uses a ETH / stETH oracle that is not displayed on the chainlink website, then the code is indeed correct (I don't think this is the case).

Auditors cannot assume protocol will wrongly name their variables in the calculation and constructor and fix the mistake by deploying the contract with an oracle not matching the name of the variable (`ettStethPriceFeed_` instead of `stethEthPriceFeed_`).

Also this is a high, not a medium since there will always be a financial loss for the protcol on withdraw, this can be abused by users withdrawing from the vault to gain a financial advantage.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> Comment from protocol https://github.com/sherlock-audit/2023-03-olympus-judging/issues/42#issuecomment-1492267023 states `1 wstETH = 1.1 stETH, 1 stETH = 0.9 ETH, and 1 OHM = 0.01 ETH`
> 
> This gives:
> - stethPerWsteth = `1.1 / 1 = 1`
> - ethPerOhm = `0.01 / 1 = 00.1`
> - stethPerEth = `1 / 0.9 = 1.1111...`
> 
> Comment also states: `The calculation as it stands now would be 1.1 * 0.9 / 0.01 = 99 OHM which is correct`
> 
> The code uses `(stethPerWsteth * stethPerEth) / (ethPerOhm * 1e9) = (1.1 / 0.9) / 0.01 = 122.222` which is incorrect:
> https://github.com/sherlock-audit/2023-03-olympus/blob/main/sherlock-olympus/src/policies/BoostedLiquidity/BLVaultManagerLido.sol#L454
> 
> The available oracle by chainlink is stETH / ETH and not ETH / stETH: https://data.chain.link/ethereum/mainnet/crypto-eth/steth-eth.
> 
> If the protocol uses a ETH / stETH oracle that is not displayed on the chainlink website, then the code is indeed correct (I don't think this is the case).
> 
> Auditors cannot assume protocol will wrongly name their variables in the calculation and constructor and fix the mistake by deploying the contract with an oracle not matching the name of the variable (`ettStethPriceFeed_` instead of `stethEthPriceFeed_`).
> 
> Also this is a high, not a medium since there will always be a financial loss for the protcol on withdraw, this can be abused by users withdrawing from the vault to gain a financial advantage.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by IAm0x52** [comment]
The variable is just named incorrectly. Math works as intended (despite the incorrect variable name) when using the stETH/ETH oracle provided by [Chainlink](https://data.chain.link/ethereum/mainnet/crypto-eth/steth-eth).

**Comment by hrishibhat** [comment]
Escalation rejected 

As pointed out the math is working as intended and incorrect variable can be considered a low issue and not a valid high/medium

**Comment by sherlock-admin** [comment]
> Escalation rejected 
> 
> As pointed out the math is working as intended and incorrect variable can be considered a low issue and not a valid high/medium

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
